elasticsearch:
  build: elasticsearch
  ports: 
   - "9200"
kibana:
  build: kibana
  ports: 
   - "5601"
  volumes:
   - ./kibana/config:/kibana-4.1.1-linux-x64/config
  links:
   - elasticsearch:es
logstash:
  build: logstash
  ports: 
   - "9000"
  links:
   - elasticsearch:es
  command: "bin/logstash -e 'input { tcp { port => 9000 } } output { elasticsearch { host => es } }'"
