elasticsearch:
  build: elasticsearch
  environment:
   - LOGSPOUT=ignore
  ports: 
   - "9200"
kibana:
  build: kibana
  ports: 
   - "5601"
  volumes:
   - ./kibana/config:/kibana-4.1.1-linux-x64/config
  environment:
   - LOGSPOUT=ignore
  links:
   - elasticsearch:es
logstash:
  build: logstash
  ports: 
   - "9000"
  links:
   - elasticsearch:es
  environment:
   - LOGSPOUT=ignore
  command: "bin/logstash -e 'input { udp { port => 9000 codec => json } } output { elasticsearch { host => es } }'"
logspout:
  build: logspout
  environment:
   - ROUTE_URIS=logstash://ls:9000
  links:
   - logstash:ls
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock
nginx:
  image: nginx
  ports:
   - "80"

